GET http://localhost:3000/pet/6615d039f79986a718f8d77e

###

POST http://localhost:3000/pet  HTTP/1.1
content-type: application/json

{
    "name": "Bis",
    "type": "Gato",
    "size": "Grande",
    "gender": "Macho",
    "bio": "O pior gato do mundo"
}